// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
import { CONDITION_OPEN, TEMPLATE_VARIABLES, hasValue, money2, type Order, type PmMark, type PmNode, type TemplateContent } from "../core";
import pdfMake from "pdfmake/build/pdfmake";
import * as fontFiles from "pdfmake/build/vfs_fonts";
import type { Content, TDocumentDefinitions } from "pdfmake/interfaces";

/** Roboto ships inside pdfmake; it covers Spanish accents and the symbols used in documents. */
const vfs = (fontFiles as unknown as { pdfMake?: { vfs: Record<string, string> }; default?: Record<string, string> }).pdfMake?.vfs ?? (fontFiles as unknown as { default: Record<string, string> }).default ?? (fontFiles as unknown as Record<string, string>);
(pdfMake as unknown as { vfs: Record<string, string> }).vfs = vfs;

const INK = "#0f0f12";
const GREEN = "#00843f";
const MUTED = "#5b5b63";
const LINE = "#e3e3e6";
const HEADING_SIZE: Record<number, number> = { 1: 16, 2: 13, 3: 11.5 };

type Values = Record<string, string>;
interface Ctx {
  values: Values;
  order: Order;
  /** Only set while drawing a header or footer. */
  page?: { page: number; pages: number };
}

const plain = (n: PmNode): string => n.text ?? (n.type === "hardBreak" ? "\n" : (n.content ?? []).map(plain).join(""));

function buildValues(order: Order): Values {
  return Object.fromEntries(TEMPLATE_VARIABLES.map((v) => [v.token, v.resolve(order)]));
}

/** {cliente} -> "Ana". Unknown tokens stay as typed so the mistake is visible. */
function fill(text: string, ctx: Ctx): string {
  return text.replace(/\{([^{}\n]+)\}/g, (whole, raw: string) => {
    const token = raw.trim();
    if (token === "pagina") return ctx.page ? String(ctx.page.page) : "";
    if (token === "paginas") return ctx.page ? String(ctx.page.pages) : "";
    return token in ctx.values ? ctx.values[token] : whole;
  });
}

/* --------------------------------------------------------------- preparing */

/**
 * Resolves the block-level markers of a list of sibling nodes:
 * {#si dato} … {/si}, {salto}, {conceptos}, and a paragraph holding only a
 * multi-line value such as {itinerario}.
 */
function prepare(nodes: PmNode[], values: Values): PmNode[] {
  const out: PmNode[] = [];
  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i];
    if (node.type !== "paragraph") {
      out.push(node.content && node.type !== "heading" ? { ...node, content: prepare(node.content, values) } : node);
      continue;
    }

    const inner = /^\{([^{}]+)\}$/.exec(plain(node).trim())?.[1].trim();
    const condition = inner ? CONDITION_OPEN.exec(inner) : null;
    if (condition) {
      let end = nodes.findIndex((n, j) => j > i && n.type === "paragraph" && plain(n).trim() === "{/si}");
      if (end < 0) end = nodes.length;
      if (hasValue(values[condition[1]] ?? "")) out.push(...prepare(nodes.slice(i + 1, end), values));
      i = end;
      continue;
    }
    if (inner === "salto") {
      out.push({ type: "pageBreak" });
      continue;
    }
    if (inner === "conceptos") {
      out.push({ type: "linesTable" });
      continue;
    }
    if (inner && inner in values) {
      // A paragraph that is only one value: skip it when empty, split it by lines when long.
      const value = values[inner].trim();
      if (!hasValue(value)) continue;
      const style = node.content?.[0]?.marks;
      for (const line of value.split("\n")) out.push({ ...node, content: line ? [{ type: "text", text: line, ...(style ? { marks: style } : {}) }] : [] });
      continue;
    }
    out.push(node);
  }
  return out;
}

/* ---------------------------------------------------------------- inline */

function markStyle(marks: PmMark[] | undefined): Record<string, unknown> {
  const style: Record<string, unknown> = {};
  const decorations: string[] = [];
  for (const mark of marks ?? []) {
    const attrs = mark.attrs ?? {};
    if (mark.type === "bold") style.bold = true;
    else if (mark.type === "italic") style.italics = true;
    else if (mark.type === "underline") decorations.push("underline");
    else if (mark.type === "strike") decorations.push("lineThrough");
    else if (mark.type === "link" && typeof attrs.href === "string" && /^https?:\/\//.test(attrs.href)) {
      style.link = attrs.href;
      style.color = "#1a56db";
      decorations.push("underline");
    } else if (mark.type === "textStyle") {
      if (typeof attrs.color === "string" && /^#[0-9a-f]{3,8}$/i.test(attrs.color)) style.color = attrs.color;
      const size = typeof attrs.fontSize === "string" ? parseFloat(attrs.fontSize) : NaN;
      if (size > 0 && size < 80) style.fontSize = size * 0.75;
    } else if (mark.type === "highlight" && typeof attrs.color === "string") style.background = attrs.color;
  }
  if (decorations.length) style.decoration = decorations.length === 1 ? decorations[0] : decorations;
  return style;
}

function runs(nodes: PmNode[] | undefined, ctx: Ctx, base: Record<string, unknown> = {}): Content[] {
  const out: Content[] = [];
  for (const n of nodes ?? []) {
    if (n.type === "text") out.push({ text: fill(n.text ?? "", ctx), ...base, ...markStyle(n.marks) } as Content);
    else if (n.type === "hardBreak") out.push({ text: "\n" });
  }
  return out;
}

const SAFE_IMAGE = /^data:image\/(png|jpe?g);base64,[A-Za-z0-9+/=]+$/;

function image(node: PmNode, alignment?: string): Content | null {
  const src = node.attrs?.src;
  if (typeof src !== "string" || !SAFE_IMAGE.test(src)) return null;
  const width = Number(node.attrs?.width);
  return { image: src, width: width > 0 ? Math.min(width * 0.75, 500) : 160, alignment: (alignment as "left") ?? "left", margin: [0, 0, 0, 6] } as Content;
}

/* ----------------------------------------------------------------- blocks */

const align = (node: PmNode) => {
  const a = node.attrs?.textAlign;
  return a === "center" || a === "right" || a === "justify" ? a : undefined;
};

function paragraph(node: PmNode, ctx: Ctx): Content[] {
  const items = node.content ?? [];
  const alignment = align(node);
  if (!items.some((i) => i.type === "image")) {
    const r = runs(items, ctx);
    return [{ text: r.length ? r : " ", alignment, margin: [0, 0, 0, 5] } as Content];
  }
  // Images cannot sit inside a line of text in pdfmake: split the paragraph around them.
  const out: Content[] = [];
  let buffer: PmNode[] = [];
  const flush = () => {
    const r = runs(buffer, ctx);
    if (r.length) out.push({ text: r, alignment, margin: [0, 0, 0, 5] } as Content);
    buffer = [];
  };
  for (const item of items) {
    if (item.type !== "image") buffer.push(item);
    else {
      flush();
      const img = image(item, alignment);
      if (img) out.push(img);
    }
  }
  flush();
  return out;
}

function listItem(node: PmNode, ctx: Ctx): Content {
  const children = convert(node.content ?? [], ctx);
  return children.length === 1 ? children[0] : ({ stack: children } as Content);
}

function table(node: PmNode, ctx: Ctx): Content {
  const rows = (node.content ?? []).map((row) =>
    (row.content ?? []).map((cell) => {
      const header = cell.type === "tableHeader";
      const stack = convert(cell.content ?? [], ctx);
      return { stack: stack.length ? stack : [{ text: " " }], bold: header || undefined, fillColor: header ? "#f4f4f5" : undefined, margin: [2, 2, 2, 0] } as Content;
    }),
  );
  const columns = Math.max(1, ...rows.map((r) => r.length));
  const first = node.content?.[0]?.content ?? [];
  const widths = Array.from({ length: columns }, (_, i) => {
    const w = Number((first[i]?.attrs?.colwidth as number[] | undefined)?.[0]);
    return w > 0 ? w * 0.75 : "*";
  });
  const bordered = node.attrs?.borders !== false;
  return {
    table: { widths: widths.some((w) => w === "*") ? widths.map(() => "*") : widths, body: rows.map((r) => [...r, ...Array(columns - r.length).fill({ text: "" })]) },
    layout: bordered ? { hLineColor: () => LINE, vLineColor: () => LINE, hLineWidth: () => 0.75, vLineWidth: () => 0.75 } : "noBorders",
    margin: [0, 2, 0, 8],
  } as Content;
}

function linesTable(ctx: Ctx): Content {
  const head = (text: string, alignment?: "right") => ({ text, bold: true, fontSize: 9.5, alignment, margin: [0, 2, 0, 2] });
  const body = [
    [head("UNIDAD"), head("RUTA Y CONCEPTO"), head("PRECIO", "right")],
    ...ctx.order.lines.map((l) => [
      { text: l.qty ? String(l.qty) : "", bold: true, margin: [0, 3, 0, 3] },
      { text: l.concept, margin: [0, 3, 0, 3] },
      { text: money2(l.amount), bold: true, alignment: "right", margin: [0, 3, 0, 3], noWrap: true },
    ]),
  ];
  const strong = (i: number, total: number) => i === 0 || i === 1 || i === total;
  return {
    table: { headerRows: 1, widths: [44, "*", 92], body },
    layout: {
      hLineWidth: (i: number, node: { table: { body: unknown[] } }) => (strong(i, node.table.body.length) ? 1.5 : 0.5),
      hLineColor: (i: number, node: { table: { body: unknown[] } }) => (strong(i, node.table.body.length) ? GREEN : LINE),
      vLineWidth: () => 0,
    },
    margin: [0, 4, 0, 8],
  } as unknown as Content;
}

function banner(node: PmNode, ctx: Ctx): Content {
  const text = runs(node.content, ctx, { color: "#ffffff", bold: true });
  return {
    table: { widths: ["*"], body: [[{ text: text.length ? text : " ", fillColor: GREEN, margin: [8, 5, 8, 5] }]] },
    layout: "noBorders",
    margin: [0, 0, 0, 8],
  } as Content;
}

function convert(nodes: PmNode[], ctx: Ctx): Content[] {
  const out: Content[] = [];
  for (const node of nodes) {
    switch (node.type) {
      case "paragraph":
        out.push(...paragraph(node, ctx));
        break;
      case "heading": {
        const level = Number(node.attrs?.level) || 1;
        out.push({ text: runs(node.content, ctx), fontSize: HEADING_SIZE[level] ?? 12, bold: true, alignment: align(node), margin: [0, 8, 0, 6] } as Content);
        break;
      }
      case "bulletList":
        out.push({ ul: (node.content ?? []).map((i) => listItem(i, ctx)), margin: [0, 0, 0, 6] } as Content);
        break;
      case "orderedList":
        out.push({ ol: (node.content ?? []).map((i) => listItem(i, ctx)), margin: [0, 0, 0, 6] } as Content);
        break;
      case "blockquote":
        out.push({ stack: convert(node.content ?? [], ctx), italics: true, color: MUTED, margin: [12, 0, 0, 5] } as Content);
        break;
      case "horizontalRule":
        out.push({ canvas: [{ type: "line", x1: 0, y1: 0, x2: 512, y2: 0, lineWidth: 0.75, lineColor: LINE }], margin: [0, 6, 0, 6] } as Content);
        break;
      case "image": {
        const img = image(node);
        if (img) out.push(img);
        break;
      }
      case "table":
        out.push(table(node, ctx));
        break;
      case "banner":
        out.push(banner(node, ctx));
        break;
      case "linesTable":
        out.push(linesTable(ctx));
        break;
      case "pageBreak":
        out.push({ text: "", pageBreak: "before" } as Content);
        break;
      default:
        if (node.content) out.push(...convert(node.content, ctx));
    }
  }
  return out;
}

/* ----------------------------------------------------------------- render */

/** Builds the PDF of an order from a document written in the editor. */
export function renderDocument(content: TemplateContent, order: Order): Promise<Uint8Array> {
  const values = buildValues(order);
  const base: Ctx = { values, order };
  const side = (doc: { content?: PmNode[] } | undefined, margin: [number, number, number, number]) =>
    doc ? (page: number, pages: number): Content => ({ margin, stack: convert(prepare(doc.content ?? [], values), { ...base, page: { page, pages } }) }) : undefined;

  const definition: TDocumentDefinitions = {
    info: { title: order.folio },
    pageSize: "LETTER",
    pageMargins: [50, content.header ? 100 : 50, 50, content.footer ? 76 : 50],
    defaultStyle: { font: "Roboto", fontSize: 10, lineHeight: 1.25, color: INK },
    header: side(content.header, [50, 28, 50, 0]),
    footer: side(content.footer, [50, 12, 50, 0]),
    content: convert(prepare(content.body.content ?? [], values), base),
  };

  return new Promise((resolve, reject) => {
    try {
      (pdfMake.createPdf(definition) as unknown as { getBuffer(done: (buffer: Uint8Array) => void): void }).getBuffer((buffer) => resolve(new Uint8Array(buffer)));
    } catch (err) {
      reject(err);
    }
  });
}
