// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
import { money2, type OrderLine, type ResolvedField } from "../core";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

/** The web editor positions fields on a 600×776 box; pages of any size are scaled to it. */
export const EDITOR_W = 600;
export const EDITOR_H = 776;

const BASE_SIZE = 10.5;
const MIN_SIZE = 6;
const PAD = 2;

/** Standard fonts only cover WinAnsi: anything else prints as "?" instead of crashing. */
function clean(font: PDFFont, text: string): string {
  const supported = new Set(font.getCharacterSet());
  // line breaks are layout, not glyphs: they survive so multi-line values (itinerary) keep their lines
  return [...text].map((ch) => (ch === "\n" || supported.has(ch.codePointAt(0) as number) ? ch : /\s/.test(ch) ? " " : "?")).join("");
}

function wrap(font: PDFFont, text: string, size: number, width: number, indent = 0): string[] {
  const out: string[] = [];
  // Only the very first line of the whole text is indented.
  const room = () => (out.length === 0 ? width - indent : width);
  for (const paragraph of text.split("\n")) {
    let line = "";
    for (const word of paragraph.split(/\s+/).filter(Boolean)) {
      const candidate = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) <= room()) {
        line = candidate;
        continue;
      }
      if (line) out.push(line);
      // a single word wider than the box gets broken by characters
      let rest = word;
      while (font.widthOfTextAtSize(rest, size) > room() && rest.length > 1) {
        let n = rest.length - 1;
        while (n > 1 && font.widthOfTextAtSize(rest.slice(0, n), size) > room()) n--;
        out.push(rest.slice(0, n));
        rest = rest.slice(n);
      }
      line = rest;
    }
    out.push(line);
  }
  return out;
}

/** Biggest size (down to MIN_SIZE) at which the text fits the box; truncates with "…" as a last resort. */
function layout(font: PDFFont, text: string, width: number, height: number, start: number, lineFactor = 1.2, indent = 0) {
  for (let size = start; size >= MIN_SIZE; size -= 0.5) {
    const lines = wrap(font, text, size, width, indent);
    if (lines.length * size * lineFactor <= height + 0.5) return { lines, size, lineFactor };
  }
  const size = MIN_SIZE;
  const max = Math.max(1, Math.floor(height / (size * lineFactor)));
  const lines = wrap(font, text, size, width, indent).slice(0, max);
  let last = lines[lines.length - 1] ?? "";
  while (last.length > 1 && font.widthOfTextAtSize(`${last}…`, size) > width) last = last.slice(0, -1);
  lines[lines.length - 1] = `${last}…`;
  return { lines, size, lineFactor };
}

const hexColor = (hex: string | undefined, fallback: ReturnType<typeof rgb>) => {
  const m = hex && /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex);
  return m ? rgb(parseInt(m[1], 16) / 255, parseInt(m[2], 16) / 255, parseInt(m[3], 16) / 255) : fallback;
};

/** Row sizes of the conceptos table: comfortable, and the tightest that still reads well. */
const ROW = 17;
const ROW_TIGHT = 11.5;

interface RowStyle {
  regular: PDFFont;
  bold: PDFFont;
  color: ReturnType<typeof rgb>;
  qtyW: number;
  amountW: number;
}

/** Draws rows of quantity, concept and amount from `topY` (PDF coordinates) downwards. */
function drawRows(page: PDFPage, style: RowStyle, x: number, topY: number, width: number, rows: OrderLine[], rowH: number, size: number) {
  rows.forEach((line, i) => {
    const baseline = topY - i * rowH - rowH * 0.7;
    if (line.qty) page.drawText(String(line.qty), { x, y: baseline, size, font: style.regular, color: style.color });
    const concept = layout(style.regular, clean(style.regular, line.concept), width - style.qtyW - style.amountW, rowH, size);
    if (concept.lines[0]) page.drawText(concept.lines[0], { x: x + style.qtyW, y: baseline, size: concept.size, font: style.regular, color: style.color });
    const amount = clean(style.bold, money2(line.amount));
    page.drawText(amount, { x: x + width - style.bold.widthOfTextAtSize(amount, size), y: baseline, size, font: style.bold, color: style.color });
  });
}

/** Prints resolved order data onto the pages of a base PDF. */
export async function renderPdf(base: Uint8Array, fields: ResolvedField[], skipPages: number[] = []): Promise<Uint8Array> {
  const pdf = await PDFDocument.load(base);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const pages = pdf.getPages();
  const ink = rgb(0.06, 0.06, 0.07);
  /** Conceptos that did not fit their box, to continue on extra pages after the page that holds the table. */
  const spill: { after: PDFPage; rows: OrderLine[]; x: number; width: number; style: RowStyle; scale: number; sy: number }[] = [];

  for (const f of fields) {
    if (skipPages.includes(f.page)) continue;
    const page = pages[f.page - 1];
    if (!page) continue;
    const { width, height } = page.getSize();
    const sx = width / EDITOR_W;
    const sy = height / EDITOR_H;
    const scale = Math.min(sx, sy);
    const boxW = f.w * sx - PAD * 2;
    const left = f.x * sx + PAD;
    const top = height - f.y * sy; // PDF y of the box top
    const boxH = f.h * sy;

    const color = hexColor(f.color, ink);
    const draw = (text: string, x: number, baselineFromTop: number, size: number, font: PDFFont) =>
      page.drawText(text, { x, y: top - baselineFromTop, size, font, color });

    if (f.type === "lines") {
      const all = f.lines ?? [];
      const style: RowStyle = { regular, bold, color, qtyW: 26 * sx, amountW: 90 * sx };
      const comfortable = ROW * sy;
      // A few more lines than the box holds: squeeze the rows. Still too many: the rest continues on extra pages.
      const rowH = all.length * comfortable <= boxH ? comfortable : Math.max(ROW_TIGHT * sy, Math.min(comfortable, boxH / all.length));
      const capacity = Math.max(1, Math.floor(boxH / rowH));
      const size = 10 * scale * Math.min(1, (rowH / comfortable) * 1.15);
      if (all.length <= capacity) {
        drawRows(page, style, left, top, boxW, all, rowH, size);
      } else {
        // The last slot of the box says that the list goes on, so nothing looks missing.
        const shown = Math.max(1, capacity - 1);
        drawRows(page, style, left, top, boxW, all.slice(0, shown), rowH, size);
        page.drawText("Continúa en la siguiente hoja", { x: left + style.qtyW, y: top - shown * rowH - rowH * 0.7, size: size * 0.85, font: regular, color: rgb(0.4, 0.4, 0.43) });
        spill.push({ after: page, rows: all.slice(shown), x: left, width: boxW, style, scale, sy });
      }
      continue;
    }

    if (!f.text) continue;
    const font = f.bold || f.type === "money" ? bold : regular;
    if (f.type === "check") {
      const size = Math.min(boxH, f.w * sx) * 0.8;
      draw("X", f.x * sx + (f.w * sx - font.widthOfTextAtSize("X", size)) / 2, boxH * 0.75, size, bold);
      continue;
    }
    const start = (f.fontSize ?? BASE_SIZE) * scale;
    // An explicit line pitch (copied from the original document) keeps replaced paragraphs aligned with their neighbours.
    const factor = f.lineHeight && f.fontSize ? f.lineHeight / f.fontSize : 1.2;
    const indent = (f.indent ?? 0) * sx;
    const { lines, size, lineFactor } = layout(font, clean(font, f.text), boxW, boxH, start, factor, indent);
    const block = lines.length * size * lineFactor;
    const startY = f.lineHeight ? 0 : (boxH - block) / 2; // copied paragraphs start at the top; new fields are centred
    lines.forEach((line, i) => {
      const width = font.widthOfTextAtSize(line, size);
      const room = i === 0 ? boxW - indent : boxW;
      const shift = i === 0 ? indent : 0;
      const x = f.align === "right" ? left + shift + room - width : f.align === "center" ? left + shift + (room - width) / 2 : left + shift;
      draw(line, x, startY + i * size * lineFactor + size * 0.95, size, font);
    });
  }

  // Continuation pages: same size as the page with the table, the remaining conceptos in the same columns.
  for (const s of spill) {
    const { width, height } = s.after.getSize();
    const rowH = ROW * s.sy;
    const top = height - 90 * s.sy;
    const capacity = Math.max(1, Math.floor((top - 50 * s.sy) / rowH));
    let after = pdf.getPages().indexOf(s.after);
    for (let from = 0; from < s.rows.length; from += capacity) {
      const extra = pdf.insertPage(++after, [width, height]);
      extra.drawText("Conceptos (continuación)", { x: s.x, y: height - 56 * s.sy, size: 13 * s.scale, font: s.style.bold, color: ink });
      extra.drawLine({ start: { x: s.x, y: height - 66 * s.sy }, end: { x: s.x + s.width, y: height - 66 * s.sy }, thickness: 1.5, color: rgb(0, 0.52, 0.25) });
      drawRows(extra, s.style, s.x, top, s.width, s.rows.slice(from, from + capacity), rowH, 10 * s.scale);
    }
  }

  // Pages that do not apply to this order (e.g. the itinerary page when there is none) are dropped last.
  [...new Set(skipPages)]
    .filter((n) => n >= 1 && n <= pages.length)
    .sort((a, b) => b - a)
    .forEach((n) => {
      const at = pdf.getPages().indexOf(pages[n - 1]);
      if (at >= 0) pdf.removePage(at);
    });

  return pdf.save();
}
