// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
/** Order folios look like OS-2026-0001; the counter restarts each year. */
export const formatFolio = (year: number, n: number) => `OS-${year}-${String(n).padStart(4, "0")}`;

export function parseFolio(folio: string): { year: number; n: number } | null {
  const m = /^OS-(\d{4})-(\d{4,})$/.exec(folio);
  return m ? { year: Number(m[1]), n: Number(m[2]) } : null;
}
