// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
/** Spanish formatting for documents. Dates are plain YYYY-MM-DD strings, never shifted by a time zone. */

const MONTHS = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"];
const WEEKDAYS = ["domingo", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado"];

const parts = (iso: string) => {
  const [y, m, d] = iso.split("-").map(Number);
  return { y, m: m ?? 1, d: d ?? 1 };
};

/** $5,000.00 */
export const money2 = (n: number) => `${n < 0 ? "-" : ""}$${Math.abs(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/** 04/10/2026 */
export const numericDate = (iso: string) => {
  const { y, m, d } = parts(iso);
  return `${String(d).padStart(2, "0")}/${String(m).padStart(2, "0")}/${y}`;
};

/** sábado 4 de octubre de 2026 */
export const longDate = (iso: string) => {
  const { y, m, d } = parts(iso);
  const weekday = WEEKDAYS[new Date(Date.UTC(y, m - 1, d)).getUTCDay()];
  return `${weekday} ${d} de ${MONTHS[m - 1]} de ${y}`;
};

/** "13:00" -> "1:00 p. m." */
export const time12 = (hhmm: string | null) => {
  if (!hhmm) return "—";
  const [h, m] = hhmm.split(":").map(Number);
  return `${h % 12 || 12}:${String(m).padStart(2, "0")} ${h < 12 ? "a. m." : "p. m."}`;
};

/** Duration between two "HH:MM" times, crossing midnight if needed. */
export const durationHours = (from: string, to: string | null) => {
  if (!to) return null;
  const toMin = (t: string) => {
    const [h, m] = t.split(":").map(Number);
    return h * 60 + m;
  };
  return ((toMin(to) - toMin(from) + 1440) % 1440) / 60;
};

export const hoursLabel = (h: number | null) => (h === null ? "—" : `${Number.isInteger(h) ? h : h.toFixed(1)} horas`);

/** "viernes" for a YYYY-MM-DD date. */
export const weekdayName = (iso: string) => {
  const { y, m, d } = parts(iso);
  return WEEKDAYS[new Date(Date.UTC(y, m - 1, d)).getUTCDay()];
};

export const monthName = (iso: string) => MONTHS[parts(iso).m - 1];

const SMALL = ["cero", "uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", "diez", "once", "doce", "trece", "catorce", "quince", "dieciséis", "diecisiete", "dieciocho", "diecinueve", "veinte", "veintiuno", "veintidós", "veintitrés", "veinticuatro", "veinticinco", "veintiséis", "veintisiete", "veintiocho", "veintinueve"];
const TENS = ["", "", "veinte", "treinta", "cuarenta", "cincuenta", "sesenta", "setenta", "ochenta", "noventa"];
const HUNDREDS = ["", "ciento", "doscientos", "trescientos", "cuatrocientos", "quinientos", "seiscientos", "setecientos", "ochocientos", "novecientos"];

/** "uno" loses its ending before a noun: un millón, veintiún mil, un peso. */
const apocope = (s: string) => s.replace(/veintiuno$/, "veintiún").replace(/uno$/, "un");

function belowThousand(n: number): string {
  if (n === 100) return "cien";
  const hundreds = Math.floor(n / 100);
  const rest = n % 100;
  const out: string[] = [];
  if (hundreds) out.push(HUNDREDS[hundreds]);
  if (rest) {
    if (rest < 30) out.push(SMALL[rest]);
    else out.push(rest % 10 ? `${TENS[Math.floor(rest / 10)]} y ${SMALL[rest % 10]}` : TENS[Math.floor(rest / 10)]);
  }
  return out.join(" ");
}

function words(n: number): string {
  if (n === 0) return "cero";
  const millions = Math.floor(n / 1_000_000);
  const thousands = Math.floor((n % 1_000_000) / 1000);
  const rest = n % 1000;
  const out: string[] = [];
  if (millions) out.push(millions === 1 ? "un millón" : `${apocope(words(millions))} millones`);
  if (thousands) out.push(thousands === 1 ? "mil" : `${apocope(belowThousand(thousands))} mil`);
  if (rest) out.push(belowThousand(rest));
  return out.join(" ");
}

/** 34000 -> "TREINTA Y CUATRO MIL PESOS 00/100 M.N." (for receipts and orders). */
export function moneyInWords(amount: number): string {
  const abs = Math.abs(amount);
  let pesos = Math.floor(abs);
  let cents = Math.round((abs - pesos) * 100);
  if (cents === 100) {
    pesos += 1;
    cents = 0;
  }
  if (pesos >= 1_000_000_000) return "";
  const unit = pesos === 1 ? "peso" : pesos > 0 && pesos % 1_000_000 === 0 ? "de pesos" : "pesos";
  return `${apocope(words(pesos))} ${unit} ${String(cents).padStart(2, "0")}/100 M.N.`.toUpperCase();
}
