// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
import { z } from "zod";
import type { OrderLine, Service, Vehicle } from "./schemas";

/* ------------------------------------------------------------------ inputs */

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Fecha inválida (AAAA-MM-DD)").refine((s) => !Number.isNaN(Date.parse(s)), "Fecha inválida");
const hhmm = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Hora inválida (HH:MM)");
const text = (max: number) => z.string().trim().min(1).max(max);

export const paymentInputSchema = z.object({
  amount: z.number().finite().positive().max(10_000_000),
  date: isoDate,
  method: z.string().trim().min(1).max(40).default("Transferencia"),
});
export type PaymentInput = z.infer<typeof paymentInputSchema>;

/** Existing client by id, or the data to create one (an existing client with the same name is reused). */
const clientRef = z.union([
  z.object({ clientId: z.string().min(1) }),
  z.object({ name: text(120), phone: z.string().trim().max(40).default(""), email: z.union([z.literal(""), z.email()]).default("") }),
]);

export const createOrderSchema = z.object({
  client: clientRef,
  serviceId: z.string().min(1),
  selections: z.record(z.string(), z.string()),
  passengers: z.number().int().positive().max(2000),
  /** Override the auto-assigned vehicle sizes. */
  units: z.array(z.number().int().positive()).optional(),
  /** Override the auto-assigned vehicles (one id per unit, in order). */
  vehicleIds: z.array(z.string()).optional(),
  route: z.enum(["round", "one-way"]),
  date: isoDate,
  departureTime: hhmm,
  returnTime: hhmm.nullable().default(null),
  origin: text(300),
  destination: text(300),
  manual: z.array(z.object({ chargeId: z.string(), qty: z.number().min(0) })).optional(),
  adjustments: z.array(z.object({ concept: text(120), amount: z.number().finite() })).optional(),
  deposit: paymentInputSchema.optional(),
  notes: z.string().trim().max(1000).optional(),
  /** Free text for the itinerary page; the document prints it only when present. */
  itinerary: z.string().trim().max(4000).optional(),
  /** Final price when it is not the recommended one from the price list; the difference is stored as an "Ajuste de precio" line. */
  priceOverride: z.number().finite().min(0).max(10_000_000).optional(),
  /** Which document to print: a template id, null for none, or omitted for the one assigned in Documentos. */
  templateId: z.string().min(1).nullable().optional(),
});
export type CreateOrderInput = z.infer<typeof createOrderSchema>;

export const patchOrderSchema = z
  .object({
    date: isoDate,
    departureTime: hhmm,
    returnTime: hhmm.nullable(),
    origin: text(300),
    destination: text(300),
    notes: z.string().trim().max(1000),
    itinerary: z.string().trim().max(4000),
    contractSigned: z.boolean(),
    /** "active" reopens a done/cancelled order (status is derived from payments again). */
    status: z.enum(["active", "done", "cancelled"]),
  })
  .partial();
export type PatchOrderInput = z.infer<typeof patchOrderSchema>;

/* ------------------------------------------------------------------- model */

export type OrderStatus = "quote" | "deposit" | "paid" | "done" | "cancelled";
/** What screens show: `late` is derived (service date passed with a balance due). */
export type OrderViewStatus = OrderStatus | "late";

export interface Payment {
  id: string;
  amount: number;
  date: string;
  method: string;
}

export interface OrderVehicle {
  capacity: number;
  vehicleId: string | null;
  code: string | null;
}

export interface Order {
  id: string;
  folio: string;
  clientId: string;
  clientName: string;
  clientPhone: string;
  clientEmail?: string;
  serviceId: string;
  serviceName: string;
  selections: Record<string, string>;
  /** Human-readable choices, e.g. "Chapala · Mismo día". */
  serviceLabel: string;
  route: "round" | "one-way";
  /** ISO date of the service. */
  date: string;
  departureTime: string;
  returnTime: string | null;
  origin: string;
  destination: string;
  passengers: number;
  units: number[];
  vehicles: OrderVehicle[];
  /** Frozen at creation: later price changes never touch existing orders. */
  lines: OrderLine[];
  total: number;
  /** What the price list recommended, kept only when the final price was changed by hand. */
  recommendedTotal?: number;
  payments: Payment[];
  status: OrderStatus;
  contractSigned: boolean;
  notes?: string;
  itinerary?: string;
  /** Document chosen when the order was created (omitted = the assigned one). Used again when the PDF is regenerated. */
  templateId?: string;
  /** ISO date the quote was issued. */
  issuedAt: string;
  createdAt: string;
  updatedAt: string;
}

const cents = (n: number) => Math.round(n * 100) / 100;

export const paidAmount = (o: Pick<Order, "payments">) => cents(o.payments.reduce((s, p) => s + p.amount, 0));
export const balanceOf = (o: Pick<Order, "payments" | "total">) => cents(o.total - paidAmount(o));

/** Status implied by the payments; done and cancelled are decided by people, so they stick. */
export function statusFromPayments(o: Pick<Order, "payments" | "total" | "status">): OrderStatus {
  if (o.status === "done" || o.status === "cancelled") return o.status;
  const paid = paidAmount(o);
  if (paid >= o.total) return "paid";
  return paid > 0 ? "deposit" : "quote";
}

export function viewStatus(o: Order, today: string): OrderViewStatus {
  const open = o.status === "quote" || o.status === "deposit";
  return open && balanceOf(o) > 0 && o.date < today ? "late" : o.status;
}

/** Today's date in Guadalajara/CDMX, as YYYY-MM-DD. */
export const todayInMexico = (now = new Date()) => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Mexico_City" }).format(now);

/** "Chapala · Mismo día · Vespertino…" from the selections that apply. */
export function describeSelections(service: Pick<Service, "variables">, selections: Record<string, string>): string {
  const matches = (cond: Record<string, string> | undefined) => Object.entries(cond ?? {}).every(([k, v]) => selections[k] === v);
  return service.variables
    .filter((v) => matches(v.showWhen))
    .map((v) => v.options.find((o) => o.value === selections[v.key])?.label)
    .filter(Boolean)
    .join(" · ");
}

/* --------------------------------------------------------------- vehicles */

/**
 * One free vehicle per unit: the smallest one that fits it (same size first), lowest code first.
 * `busy` = vehicles already booked that day. Units with nobody available get vehicleId null.
 */
export function assignVehicles(units: number[], vehicles: Vehicle[], busy: Set<string>): OrderVehicle[] {
  const taken = new Set(busy);
  const pool = [...vehicles].sort((a, b) => a.capacity - b.capacity || a.code.localeCompare(b.code, "es", { numeric: true }));
  return units.map((capacity) => {
    // the exact size first; otherwise the smallest free vehicle that still fits everyone
    const pick = pool.find((v) => v.capacity >= capacity && !taken.has(v.id));
    if (pick) taken.add(pick.id);
    return { capacity, vehicleId: pick?.id ?? null, code: pick?.code ?? null };
  });
}

export function vehicleStats(vehicleId: string, orders: Order[], today: string) {
  const mine = orders.filter((o) => o.status !== "cancelled" && o.vehicles.some((v) => v.vehicleId === vehicleId));
  const month = today.slice(0, 7);
  return {
    servicesThisMonth: mine.filter((o) => o.date.startsWith(month)).length,
    nextService: mine.map((o) => o.date).filter((d) => d >= today).sort()[0] ?? null,
  };
}

/* ---------------------------------------------------------------- clients */

/** Numbers shown on the Clientes screen, derived from that client's orders. */
export function clientStats(orders: Order[], today: string) {
  const live = orders.filter((o) => o.status !== "cancelled");
  const due = live.filter((o) => o.status !== "done" || balanceOf(o) > 0);
  const upcoming = live.filter((o) => o.date >= today).sort((a, b) => a.date.localeCompare(b.date))[0];
  const last = upcoming ?? [...live].sort((a, b) => b.date.localeCompare(a.date))[0];
  return {
    servicesCount: live.length,
    totalContracted: cents(live.reduce((s, o) => s + o.total, 0)),
    balanceDue: cents(due.reduce((s, o) => s + balanceOf(o), 0)),
    balanceLate: live.some((o) => viewStatus(o, today) === "late"),
    lastService: last ? { label: `${last.serviceName} · ${last.destination}`, when: last.date } : null,
  };
}

/* ---------------------------------------------------------------- summary */

export interface MonthSummary {
  /** ISO month, e.g. "2026-09". Orders are grouped by service date. */
  month: string;
  quoted: number;
  /** Payments received with a payment date inside the month. */
  earned: number;
  quotedByService: Record<string, number>;
  /** Everything still owed, across all months. */
  receivable: number;
  lateOrders: number;
  upcoming7d: number;
  upcoming: { orderId: string; folio: string; date: string; clientName: string; serviceName: string }[];
}

export function summarizeMonth(orders: Order[], month: string, today: string): MonthSummary {
  const live = orders.filter((o) => o.status !== "cancelled");
  const inMonth = live.filter((o) => o.date.startsWith(month));
  const quotedByService: Record<string, number> = {};
  for (const o of inMonth) quotedByService[o.serviceName] = cents((quotedByService[o.serviceName] ?? 0) + o.total);

  const weekAhead = new Date(`${today}T00:00:00Z`);
  weekAhead.setUTCDate(weekAhead.getUTCDate() + 7);
  const limit = weekAhead.toISOString().slice(0, 10);
  const upcoming = live.filter((o) => o.date >= today && o.date <= limit && o.status !== "done").sort((a, b) => a.date.localeCompare(b.date));

  return {
    month,
    quoted: cents(inMonth.reduce((s, o) => s + o.total, 0)),
    earned: cents(live.flatMap((o) => o.payments).filter((p) => p.date.startsWith(month)).reduce((s, p) => s + p.amount, 0)),
    quotedByService,
    receivable: cents(live.reduce((s, o) => s + balanceOf(o), 0)),
    lateOrders: live.filter((o) => viewStatus(o, today) === "late").length,
    upcoming7d: upcoming.length,
    upcoming: upcoming.slice(0, 5).map((o) => ({ orderId: o.id, folio: o.folio, date: o.date, clientName: o.clientName, serviceName: o.serviceName })),
  };
}
