// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
import type { Charge, OrderLine, PriceRow, ServiceInput } from "./schemas";
import { DEFAULT_FLEET, unitLabel, type FleetUnit } from "./units";

export interface QuoteInput {
  /** variable key -> option value */
  selections: Record<string, string>;
  /** Capacity of each assigned vehicle, e.g. [14, 14, 6]. */
  units: number[];
  routeLabel?: string;
  /** Quantities for manual charges (extra hours, extra moves…). */
  manual?: { chargeId: string; qty: number }[];
  /** Free-form lines such as a discount (negative amount). */
  adjustments?: { concept: string; amount: number }[];
}

export interface Quote {
  lines: OrderLine[];
  total: number;
  /** Capacities that have no price for the chosen selections. */
  unpriced: number[];
  errors: string[];
  /** True when the quote can be turned into an order. */
  ok: boolean;
}

type PricedService = Pick<ServiceInput, "name" | "variables" | "prices" | "charges">;

const matches = (cond: Record<string, string> | undefined, selections: Record<string, string>) =>
  Object.entries(cond ?? {}).every(([k, v]) => selections[k] === v);

const cents = (n: number) => Math.round(n * 100) / 100;

/** The most specific row whose `sel` fits the selections wins. */
function findPrice(prices: PriceRow[], capacity: number, selections: Record<string, string>): number | null {
  let best: PriceRow | null = null;
  for (const row of prices) {
    if (row.capacity !== capacity || !matches(row.sel, selections)) continue;
    if (!best || Object.keys(row.sel).length > Object.keys(best.sel).length) best = row;
  }
  return best ? best.price : null;
}

function chargeAmount(charge: Charge, units: number[]): number {
  const of = (capacity: number) => charge.amounts[String(capacity)] ?? charge.amounts["*"] ?? 0;
  return charge.perUnit ? units.reduce((sum, c) => sum + of(c), 0) : (charge.amounts["*"] ?? 0);
}

/** Prices an order from a service definition. Pure: same input, same quote. */
export function quote(service: PricedService, input: QuoteInput, fleet: FleetUnit[] = DEFAULT_FLEET): Quote {
  const { selections, units } = input;
  const errors: string[] = [];
  const lines: OrderLine[] = [];
  const unpriced: number[] = [];

  const active = service.variables.filter((v) => matches(v.showWhen, selections));
  for (const v of active) {
    const picked = selections[v.key];
    if (!picked) errors.push(`Falta elegir ${v.label}.`);
    else if (!v.options.some((o) => o.value === picked)) errors.push(`"${picked}" no es una opción válida de ${v.label}.`);
  }
  if (!units.length) errors.push("No hay unidades asignadas.");

  const effective = Object.fromEntries(active.filter((v) => selections[v.key]).map((v) => [v.key, selections[v.key]]));
  const optionLabels = active.map((v) => v.options.find((o) => o.value === selections[v.key])?.label).filter(Boolean);
  const detail = [service.name, ...optionLabels].join(" · ");
  const route = input.routeLabel ? `${input.routeLabel} · ` : "";

  const byCapacity = new Map<number, number>();
  for (const c of units) byCapacity.set(c, (byCapacity.get(c) ?? 0) + 1);
  if (!errors.length) {
    for (const [capacity, qty] of byCapacity) {
      const price = findPrice(service.prices, capacity, effective);
      if (price === null) {
        unpriced.push(capacity);
        continue;
      }
      lines.push({ qty, concept: `${unitLabel(capacity, fleet)} pasajeros · ${route}${detail}`, amount: cents(price * qty) });
    }
    for (const c of unpriced) errors.push(`No hay precio para ${unitLabel(c, fleet)} con estas opciones.`);
  }

  if (!errors.length) {
    for (const charge of service.charges) {
      if (charge.mode !== "conditional" || !matches(charge.when, effective)) continue;
      const amount = chargeAmount(charge, units);
      if (amount) lines.push({ qty: null, concept: charge.label, amount: cents(amount) });
    }
    for (const { chargeId, qty } of input.manual ?? []) {
      if (!(qty > 0)) continue;
      const charge = service.charges.find((c) => c.id === chargeId && c.mode === "manual");
      if (!charge) {
        errors.push(`El cargo "${chargeId}" no existe en este servicio.`);
        continue;
      }
      const amount = chargeAmount(charge, units) * qty;
      if (amount) lines.push({ qty: null, concept: `${charge.label} (${qty})`, amount: cents(amount) });
    }
    for (const adj of input.adjustments ?? []) {
      if (adj.amount) lines.push({ qty: null, concept: adj.concept, amount: cents(adj.amount) });
    }
  }

  const total = cents(lines.reduce((sum, l) => sum + l.amount, 0));
  return { lines, total, unpriced, errors, ok: errors.length === 0 };
}
