// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
import type { Order } from "./orders";

/** A complete order used to preview documents when there is no real order to show. */
export const SAMPLE_ORDER: Order = {
  id: "sample",
  folio: "OS-2026-0000",
  clientId: "sample-client",
  clientName: "Tamiko Perez Gasque Muslera",
  clientPhone: "33 1234 5678",
  serviceId: "sample-service",
  serviceName: "Turismo",
  selections: {},
  serviceLabel: "Ciudad de México · 4 días",
  route: "round",
  date: "2026-10-06",
  departureTime: "10:00",
  returnTime: "17:00",
  origin: "UNIVERSIDAD MARISTA - M. Champagnat #2981, Loma Bonita, 45050 Zapopan, Jal.",
  destination: "Ciudad de México, CDMX",
  passengers: 18,
  units: [20],
  vehicles: [],
  lines: [
    { qty: 1, concept: "Van 20 pasajeros · Ida y vuelta · Turismo · Ciudad de México · 4 días", amount: 35000 },
    { qty: null, concept: "Descuento", amount: -1000 },
  ],
  total: 34000,
  payments: [{ id: "sample-payment", amount: 7750, date: "2026-09-20", method: "Transferencia" }],
  status: "deposit",
  contractSigned: false,
  notes: "Hotel City Express Iztapalapa.",
  itinerary:
    "Día 1 (06/10/2026)\n- Salida por la mañana a las 10:00 hrs. rumbo a la CDMX\n- Llegada a un parador turístico para desayunar o comer\n- Llegada al hotel aproximadamente a las 18:00 hrs.\n\nDía 2 (07/10/2026)\n- Salida del hotel a las 07:30 hrs.\n- Regreso al hotel 4:00 o 5:00 pm.",
  issuedAt: "2026-09-30",
  createdAt: "",
  updatedAt: "",
};
