// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
import { z } from "zod";

/**
 * Data model. Everything the operator edits (services, variables, prices,
 * charges) is plain data validated here, so the pricing engine never has to
 * know what "Amatitán" or "Turismo" mean.
 */

const slug = z.string().regex(/^[a-z0-9][a-z0-9_-]{0,39}$/, "Solo minúsculas, números, guion y guion bajo (máx. 40)");
const text = (max: number) => z.string().trim().min(1).max(max);
const money = z.number().finite().min(0).max(10_000_000);

/* ------------------------------------------------------------------ service */

export const variableSchema = z.object({
  key: slug,
  label: text(60),
  options: z.array(z.object({ value: slug, label: text(80) })).min(1).max(100),
  /** The variable only applies (and is only required) when these selections match. */
  showWhen: z.record(z.string(), z.string()).optional(),
});

/** One price: for a vehicle capacity, when every `sel` entry matches the order's selections. */
export const priceRowSchema = z.object({
  sel: z.record(z.string(), z.string()),
  capacity: z.number().int().min(1).max(200),
  price: money,
});

/**
 * Extra amount on top of the base price.
 * - manual: the operator enters a quantity (extra hours, extra moves).
 * - conditional: applied automatically when `when` matches the selections (schedule surcharges).
 * `amounts` is keyed by vehicle capacity ("14": 500) with "*" as fallback / flat amount.
 * perUnit: charged once per assigned vehicle instead of once per order.
 */
export const chargeSchema = z.object({
  id: slug,
  label: text(80),
  mode: z.enum(["manual", "conditional"]),
  perUnit: z.boolean(),
  amounts: z.record(z.string(), money),
  when: z.record(z.string(), z.string()).optional(),
});

export const serviceInputSchema = z.object({
  name: text(80),
  description: z.string().trim().max(500).optional(),
  active: z.boolean().default(true),
  variables: z.array(variableSchema).max(10),
  prices: z.array(priceRowSchema).max(2000),
  charges: z.array(chargeSchema).max(30),
});

export type Variable = z.infer<typeof variableSchema>;
export type PriceRow = z.infer<typeof priceRowSchema>;
export type Charge = z.infer<typeof chargeSchema>;
export type ServiceInput = z.infer<typeof serviceInputSchema>;
export type Service = ServiceInput & { id: string; createdAt: string; updatedAt: string };

/** Cross-field checks a schema cannot express. Returns human-readable problems. */
export function validateService(service: ServiceInput): string[] {
  const problems: string[] = [];
  const vars = new Map(service.variables.map((v) => [v.key, v]));
  if (vars.size !== service.variables.length) problems.push("Hay variables con la misma clave.");

  const options = (key: string) => new Set(vars.get(key)?.options.map((o) => o.value));
  for (const v of service.variables) {
    if (new Set(v.options.map((o) => o.value)).size !== v.options.length) problems.push(`"${v.label}" tiene opciones repetidas.`);
  }

  const checkRefs = (where: string, refs: Record<string, string> | undefined) => {
    for (const [k, val] of Object.entries(refs ?? {})) {
      if (!vars.has(k)) problems.push(`${where}: la variable "${k}" no existe.`);
      else if (!options(k).has(val)) problems.push(`${where}: "${val}" no es una opción de "${k}".`);
    }
  };
  for (const v of service.variables) checkRefs(`Variable "${v.label}"`, v.showWhen);
  for (const c of service.charges) checkRefs(`Cargo "${c.label}"`, c.when);

  if (new Set(service.charges.map((c) => c.id)).size !== service.charges.length) problems.push("Hay cargos con el mismo id.");
  for (const c of service.charges) {
    if (c.mode === "conditional" && !Object.keys(c.when ?? {}).length) problems.push(`El cargo "${c.label}" es condicional y necesita una condición.`);
  }

  const seen = new Set<string>();
  service.prices.forEach((row, i) => {
    checkRefs(`Precio #${i + 1}`, row.sel);
    const key = `${row.capacity}|${Object.keys(row.sel).sort().map((k) => `${k}=${row.sel[k]}`).join("&")}`;
    if (seen.has(key)) problems.push(`Precio #${i + 1} está duplicado.`);
    seen.add(key);
  });
  return problems;
}

/* ------------------------------------------------------------------ client */

export const clientInputSchema = z.object({
  name: text(120),
  phone: z.string().trim().max(40).default(""),
  email: z.union([z.literal(""), z.email()]).default(""),
  contractSigned: z.boolean().default(false),
});
export type ClientInput = z.infer<typeof clientInputSchema>;

export interface Client extends ClientInput {
  id: string;
  /** Maintained when orders and payments are written. */
  servicesCount: number;
  totalContracted: number;
  balanceDue: number;
  balanceLate: boolean;
  lastService?: { label: string; when: string } | null;
  createdAt: string;
  updatedAt: string;
}

/* ----------------------------------------------------------------- vehicle */

export const vehicleInputSchema = z.object({
  code: text(20),
  /** Top of the range of passengers this vehicle takes. */
  capacity: z.number().int().min(1).max(200),
  /** Bottom of the range; vehicles saved before ranges existed fall back to the standard sizes. */
  minCapacity: z.number().int().min(1).max(200).optional(),
  kind: z.enum(["car", "suv", "minivan", "van", "microbus", "midibus", "bus"]),
  model: z.string().trim().max(80).default(""),
  plates: z.string().trim().max(20).default(""),
  driver: z.string().trim().max(80).nullable().default(null),
  active: z.boolean().default(true),
});
export type VehicleInput = z.infer<typeof vehicleInputSchema>;
export type Vehicle = VehicleInput & { id: string; createdAt: string; updatedAt: string };

const STANDARD_SIZES = [6, 14, 20, 45];

/** The passengers a vehicle takes, as [from, to]. */
export function vehicleRange(v: Pick<VehicleInput, "capacity" | "minCapacity">): [number, number] {
  const i = STANDARD_SIZES.indexOf(v.capacity);
  return [v.minCapacity ?? (i > 0 ? STANDARD_SIZES[i - 1] + 1 : 1), v.capacity];
}

/**
 * Ranges are categories: several vehicles can share exactly the same range,
 * but two different ranges cannot overlap. Returns the clashing vehicle, if any.
 */
export function rangeConflict<T extends Pick<VehicleInput, "capacity" | "minCapacity">>(mine: Pick<VehicleInput, "capacity" | "minCapacity">, others: T[]): T | undefined {
  const [a, b] = vehicleRange(mine);
  return others.find((o) => {
    const [c, d] = vehicleRange(o);
    return !(a === c && b === d) && a <= d && c <= b;
  });
}

/* ------------------------------------------------------------------- order */

export interface OrderLine {
  qty: number | null;
  concept: string;
  /** Line total; negative for discounts. */
  amount: number;
}
