// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
import { z } from "zod";
import { durationHours, hoursLabel, longDate, monthName, money2, moneyInWords, numericDate, time12, weekdayName } from "./format";
import { balanceOf, paidAmount, todayInMexico, type Order } from "./orders";
import type { OrderLine } from "./schemas";

/* ----------------------------------------------------------------- schemas */

export const fieldTypeSchema = z.enum(["text", "date", "money", "sign", "check", "lines"]);
export type FieldType = z.infer<typeof fieldTypeSchema>;

/** Position and size in points on a 600×776 page, origin top-left (the editor's box). */
export const templateFieldSchema = z.object({
  id: z.string().min(1).max(60),
  page: z.number().int().min(1).max(50),
  label: z.string().trim().max(80).default(""),
  /** Order variable that fills the field; null = not mapped yet (left blank). Used when `text` is empty. */
  variable: z.string().nullable(),
  type: fieldTypeSchema,
  /** What the field prints: plain text with {variables}, e.g. "Fecha: {fecha}". Wins over `variable`. */
  text: z.string().max(2000).optional(),
  /** Patch color that hides the original text underneath (applied when the page is flattened). */
  cover: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  /** Exact areas to patch when the original text is several lines that do not fill the box (e.g. a label stays on the first line). Defaults to the whole box. */
  coverRects: z.array(z.object({ x: z.number(), y: z.number(), w: z.number().positive(), h: z.number().positive() })).max(30).optional(),
  /** Gap before the first line, for paragraphs that start after a label. */
  indent: z.number().min(0).max(600).optional(),
  /** Text size in editor points, line pitch for multi-line text, weight, alignment and color. */
  fontSize: z.number().min(4).max(72).optional(),
  lineHeight: z.number().min(4).max(120).optional(),
  bold: z.boolean().optional(),
  align: z.enum(["left", "center", "right"]).optional(),
  color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  x: z.number().finite(),
  y: z.number().finite(),
  w: z.number().finite().positive(),
  h: z.number().finite().positive(),
  required: z.boolean().default(false),
});
export type TemplateField = z.infer<typeof templateFieldSchema>;

/* A document is ProseMirror JSON (what the TipTap editor produces). */

export interface PmMark {
  type: string;
  attrs?: Record<string, unknown>;
}

export interface PmNode {
  type: string;
  attrs?: Record<string, unknown>;
  content?: PmNode[];
  text?: string;
  marks?: PmMark[];
}

const pmMarkSchema = z.object({ type: z.string().max(40), attrs: z.record(z.string(), z.unknown()).optional() });
export const pmNodeSchema: z.ZodType<PmNode> = z.lazy(() =>
  z.object({
    type: z.string().max(40),
    attrs: z.record(z.string(), z.unknown()).optional(),
    content: z.array(pmNodeSchema).optional(),
    text: z.string().max(20_000).optional(),
    marks: z.array(pmMarkSchema).optional(),
  }),
);

/** Body plus optional header and footer repeated on every page. */
export const templateContentSchema = z.object({
  body: pmNodeSchema,
  header: pmNodeSchema.optional(),
  footer: pmNodeSchema.optional(),
});
export type TemplateContent = z.infer<typeof templateContentSchema>;

/**
 * mode "pdf": a blank PDF plus positioned fields (for formats that must stay as they are).
 * mode "document": written in the editor with {variables}; the PDF is built when the order is created.
 */
export const templateInputSchema = z.object({
  name: z.string().trim().min(1).max(120),
  kind: z.enum(["order", "contract", "receipt", "other"]),
  trigger: z.enum(["quote", "deposit", "payment", "manual"]),
  mode: z.enum(["pdf", "document"]).default("pdf"),
  fileName: z.string().trim().max(200).default(""),
  pages: z.number().int().min(1).max(50).default(1),
  fields: z.array(templateFieldSchema).max(200).default([]),
  /** PDF mode: pages that print only when the order has that data, e.g. the itinerary page. */
  pageRules: z.array(z.object({ page: z.number().int().min(1).max(50), onlyIf: z.string().min(1).max(40) })).max(50).optional(),
  content: templateContentSchema.optional(),
  status: z.enum(["published", "draft"]).default("draft"),
  sendByWhatsApp: z.boolean().default(false),
  requestSignature: z.boolean().default(false),
});
export type TemplateInput = z.infer<typeof templateInputSchema>;

export type DocumentTemplate = TemplateInput & {
  id: string;
  /** S3 key of the base PDF (mode "pdf"); null until one is uploaded. Pages with covers are flattened images. */
  fileKey: string | null;
  /** The PDF as uploaded, kept so the text can be edited again after flattening; null when it is the same as fileKey. */
  sourceKey?: string | null;
  createdAt: string;
  updatedAt: string;
};

export interface GeneratedDocument {
  id: string;
  templateId: string;
  templateName: string;
  orderId: string;
  orderFolio: string;
  clientName: string;
  /** ISO datetime. */
  createdAt: string;
  channel: "Descarga";
  fileKey: string;
  fileName: string;
}

/** Which template each purpose uses. The order template is generated for every new order. */
export interface Assignments {
  order: string | null;
}

/* --------------------------------------------------------------- variables */

export interface TemplateVariable {
  id: string;
  /** What is typed in a document: {cliente}. */
  token: string;
  label: string;
  type: FieldType;
  resolve: (o: Order) => string;
}

const unitsText = (units: number[]) => {
  const count = new Map<number, number>();
  for (const c of units) count.set(c, (count.get(c) ?? 0) + 1);
  return [...count]
    .map(([capacity, n]) => `${n} ${capacity >= 45 ? (n > 1 ? "autobuses" : "autobús") : n > 1 ? "vans" : "van"} de ${capacity} pasajeros`)
    .join(" y ");
};

const cents = (n: number) => Math.round(n * 100) / 100;
const discountOf = (o: Order) => cents(-o.lines.filter((l) => l.amount < 0).reduce((s, l) => s + l.amount, 0));
const subtotalOf = (o: Order) => cents(o.lines.filter((l) => l.amount > 0).reduce((s, l) => s + l.amount, 0));
const STATUS_LABEL: Record<string, string> = { quote: "Cotización", deposit: "Con anticipo", paid: "Liquidada", done: "Realizada", cancelled: "Cancelada" };
const datePart = (iso: string, at: 0 | 1 | 2) => String(Number(iso.split("-")[at]));
const first = <T,>(list: T[]) => list[0];
const last = <T,>(list: T[]) => list[list.length - 1];

/** True when a value is worth printing: not empty and not a zero amount ("$0.00"). Drives {#si …} and optional pages. */
export const hasValue = (value: string) => {
  const s = value.trim();
  return s !== "" && !/^-?\$?\s?0+(\.0+)?$/.test(s);
};

/** Order data a template can print. `id` is used by PDF fields, `token` by documents. */
export const TEMPLATE_VARIABLES: TemplateVariable[] = [
  { id: "client.name", token: "cliente", label: "Cliente · nombre", type: "text", resolve: (o) => o.clientName },
  { id: "client.phone", token: "celular", label: "Cliente · celular", type: "text", resolve: (o) => o.clientPhone },
  { id: "order.folio", token: "folio", label: "Orden · folio", type: "text", resolve: (o) => o.folio },
  { id: "order.issued", token: "emision", label: "Orden · fecha de emisión", type: "date", resolve: (o) => numericDate(o.issuedAt) },
  { id: "order.notes", token: "notas", label: "Orden · notas", type: "text", resolve: (o) => o.notes ?? "" },
  { id: "order.itinerary", token: "itinerario", label: "Orden · itinerario", type: "text", resolve: (o) => o.itinerary ?? "" },
  { id: "order.passengers", token: "pasajeros", label: "Orden · número de pasajeros", type: "text", resolve: (o) => String(o.passengers) },
  { id: "order.lines", token: "conceptos", label: "Orden · tabla de conceptos y precios", type: "lines", resolve: (o) => o.lines.map((l) => l.concept).join("\n") },
  { id: "service.name", token: "servicio", label: "Servicio · nombre", type: "text", resolve: (o) => o.serviceName },
  { id: "service.label", token: "detalle", label: "Servicio · detalle", type: "text", resolve: (o) => [o.serviceName, o.serviceLabel].filter(Boolean).join(" · ") },
  { id: "service.date", token: "fecha", label: "Servicio · fecha", type: "date", resolve: (o) => longDate(o.date) },
  { id: "service.dateShort", token: "fecha_corta", label: "Servicio · fecha (00/00/0000)", type: "date", resolve: (o) => numericDate(o.date) },
  { id: "service.time", token: "horario", label: "Servicio · horario", type: "text", resolve: (o) => `${time12(o.departureTime)} – ${time12(o.returnTime)}` },
  { id: "service.departure", token: "ida", label: "Servicio · hora de salida", type: "text", resolve: (o) => time12(o.departureTime) },
  { id: "service.return", token: "regreso", label: "Servicio · hora de regreso", type: "text", resolve: (o) => (o.route === "round" ? time12(o.returnTime) : "Sin regreso") },
  { id: "service.duration", token: "duracion", label: "Servicio · duración", type: "text", resolve: (o) => (o.route === "round" ? hoursLabel(durationHours(o.departureTime, o.returnTime)) : "—") },
  { id: "service.route", token: "ruta", label: "Servicio · ruta", type: "text", resolve: (o) => (o.route === "round" ? "Ida y vuelta" : "Solo ida") },
  { id: "service.origin", token: "salida", label: "Servicio · dirección de salida", type: "text", resolve: (o) => o.origin },
  { id: "service.destination", token: "destino", label: "Servicio · destino", type: "text", resolve: (o) => o.destination },
  { id: "unit.capacity", token: "unidad", label: "Unidad · capacidad", type: "text", resolve: (o) => unitsText(o.units) },
  { id: "pay.total", token: "total", label: "Pago · total", type: "money", resolve: (o) => money2(o.total) },
  { id: "pay.paid", token: "anticipo", label: "Pago · abonado", type: "money", resolve: (o) => money2(paidAmount(o)) },
  { id: "pay.paidDetail", token: "abonos", label: "Pago · abonos con fecha", type: "text", resolve: (o) => o.payments.map((p) => `Abonado: ${money2(p.amount)} (${numericDate(p.date)})`).join(" · ") },
  { id: "pay.due", token: "pendiente", label: "Pago · por liquidar", type: "money", resolve: (o) => money2(balanceOf(o)) },
  { id: "sign.client", token: "firma", label: "Firma del cliente", type: "sign", resolve: () => "" },

  // Everything else an order carries, so a template can print any of it.
  { id: "client.email", token: "correo", label: "Cliente · correo", type: "text", resolve: (o) => o.clientEmail ?? "" },
  { id: "order.discount", token: "descuento", label: "Orden · descuento", type: "money", resolve: (o) => money2(discountOf(o)) },
  { id: "order.recommended", token: "precio_recomendado", label: "Orden · precio recomendado (si se cambió el precio)", type: "money", resolve: (o) => (o.recommendedTotal !== undefined ? money2(o.recommendedTotal) : "") },
  { id: "order.subtotal", token: "subtotal", label: "Orden · subtotal (antes del descuento)", type: "money", resolve: (o) => money2(subtotalOf(o)) },
  { id: "order.status", token: "estado", label: "Orden · estado", type: "text", resolve: (o) => STATUS_LABEL[o.status] ?? o.status },
  { id: "order.contract", token: "contrato", label: "Orden · contrato", type: "text", resolve: (o) => (o.contractSigned ? "Firmado" : "Pendiente de firma") },
  { id: "order.issuedLong", token: "emision_larga", label: "Orden · fecha de emisión (con día y mes)", type: "date", resolve: (o) => longDate(o.issuedAt) },
  { id: "order.today", token: "hoy", label: "Hoy (fecha en que se genera el PDF)", type: "date", resolve: () => numericDate(todayInMexico()) },
  { id: "order.linesText", token: "conceptos_texto", label: "Orden · conceptos en texto", type: "text", resolve: (o) => o.lines.map((l) => `${l.qty ? `${l.qty} × ` : ""}${l.concept}: ${money2(l.amount)}`).join("\n") },
  { id: "service.options", token: "opciones", label: "Servicio · opciones elegidas", type: "text", resolve: (o) => o.serviceLabel },
  { id: "service.weekday", token: "dia_semana", label: "Servicio · día de la semana", type: "text", resolve: (o) => weekdayName(o.date) },
  { id: "service.day", token: "dia", label: "Servicio · día del mes", type: "text", resolve: (o) => datePart(o.date, 2) },
  { id: "service.month", token: "mes", label: "Servicio · mes", type: "text", resolve: (o) => monthName(o.date) },
  { id: "service.year", token: "anio", label: "Servicio · año", type: "text", resolve: (o) => datePart(o.date, 0) },
  { id: "unit.vehicles", token: "vehiculos", label: "Unidad · vehículos asignados", type: "text", resolve: (o) => o.vehicles.map((v) => v.code).filter(Boolean).join(", ") },
  { id: "unit.count", token: "num_unidades", label: "Unidad · número de unidades", type: "text", resolve: (o) => String(o.units.length) },
  { id: "unit.seats", token: "lugares", label: "Unidad · lugares totales", type: "text", resolve: (o) => String(o.units.reduce((s, c) => s + c, 0)) },
  { id: "pay.count", token: "num_abonos", label: "Pago · número de abonos", type: "text", resolve: (o) => String(o.payments.length) },
  { id: "pay.first", token: "primer_abono", label: "Pago · monto del primer abono", type: "money", resolve: (o) => (o.payments.length ? money2(first(o.payments).amount) : "") },
  { id: "pay.firstDate", token: "fecha_primer_abono", label: "Pago · fecha del primer abono", type: "date", resolve: (o) => (o.payments.length ? numericDate(first(o.payments).date) : "") },
  { id: "pay.last", token: "ultimo_abono", label: "Pago · monto del último abono", type: "money", resolve: (o) => (o.payments.length ? money2(last(o.payments).amount) : "") },
  { id: "pay.lastDate", token: "fecha_ultimo_abono", label: "Pago · fecha del último abono", type: "date", resolve: (o) => (o.payments.length ? numericDate(last(o.payments).date) : "") },
  { id: "pay.method", token: "metodo_pago", label: "Pago · método del último abono", type: "text", resolve: (o) => (o.payments.length ? last(o.payments).method : "") },
  { id: "pay.percent", token: "porcentaje_pagado", label: "Pago · porcentaje pagado", type: "text", resolve: (o) => (o.total > 0 ? `${Math.round((paidAmount(o) / o.total) * 100)}%` : "0%") },
  { id: "pay.totalWords", token: "total_letra", label: "Pago · total con letra", type: "text", resolve: (o) => moneyInWords(o.total) },
  { id: "pay.dueWords", token: "pendiente_letra", label: "Pago · por liquidar con letra", type: "text", resolve: (o) => moneyInWords(balanceOf(o)) },
];

const byId = new Map(TEMPLATE_VARIABLES.map((v) => [v.id, v]));
const TEXT_TOKEN = /\{([^{}\n]+)\}/g;
export const variableByToken = new Map(TEMPLATE_VARIABLES.map((v) => [v.token, v]));

/** "Fecha: {fecha}" -> "Fecha: martes 6 de octubre…". Unknown tokens stay as typed. */
export function fillText(order: Order, text: string): string {
  return text.replace(TEXT_TOKEN, (whole, raw: string) => variableByToken.get(raw.trim())?.resolve(order) ?? whole);
}

/** Markers that are not order data. */
export const SPECIAL_TOKENS = [
  { token: "pagina", label: "Número de página" },
  { token: "paginas", label: "Total de páginas" },
  { token: "salto", label: "Salto de página (en un párrafo solo)" },
] as const;

/** {#si itinerario} … {/si}: the lines in between print only when that data is not empty. */
export const CONDITION_OPEN = /^#si\s+([a-z_]+)$/;
export const CONDITION_CLOSE = "/si";

const TOKEN_PATTERN = /\{([^{}\n]+)\}/g;

function collectText(node: PmNode | undefined, out: string[]) {
  if (!node) return;
  if (node.text) out.push(node.text);
  node.content?.forEach((c) => collectText(c, out));
}

/** Everything typed between braces in a document, to catch typos before they print. */
export function unknownTokens(content: TemplateContent): string[] {
  const text: string[] = [];
  for (const part of [content.body, content.header, content.footer]) collectText(part, text);
  const bad = new Set<string>();
  for (const [, raw] of text.join("\n").matchAll(TOKEN_PATTERN)) {
    const token = raw.trim();
    const open = CONDITION_OPEN.exec(token);
    const known = variableByToken.has(token) || SPECIAL_TOKENS.some((s) => s.token === token) || token === CONDITION_CLOSE || (open !== null && variableByToken.has(open[1]));
    if (!known) bad.add(token);
  }
  return [...bad];
}

/** Problems that would make a template fail or print blanks. */
export function validateTemplate(input: TemplateInput): string[] {
  const problems: string[] = [];
  if (input.mode === "document") {
    if (!input.content) return ["El documento está vacío."];
    if (JSON.stringify(input.content).length > 350_000) problems.push("El documento pesa demasiado (imágenes muy grandes).");
    for (const token of unknownTokens(input.content)) problems.push(`Dato desconocido: {${token}}.`);
    return problems;
  }
  for (const rule of input.pageRules ?? []) {
    if (!variableByToken.has(rule.onlyIf)) problems.push(`La página ${rule.page} depende de un dato desconocido: {${rule.onlyIf}}.`);
    if (rule.page > input.pages) problems.push(`Hay una regla para la página ${rule.page} pero el PDF tiene ${input.pages}.`);
  }
  const ids = new Set<string>();
  for (const f of input.fields) {
    if (ids.has(f.id)) problems.push(`Campo repetido: ${f.id}.`);
    ids.add(f.id);
    if (f.page > input.pages) problems.push(`El campo "${f.label || f.id}" está en la página ${f.page} pero el PDF tiene ${input.pages}.`);
    if (f.variable !== null && !byId.has(f.variable)) problems.push(`El campo "${f.label || f.id}" usa un dato desconocido: ${f.variable}.`);
    for (const [, raw] of (f.text ?? "").matchAll(TEXT_TOKEN)) {
      if (!variableByToken.has(raw.trim())) problems.push(`El campo "${f.label || f.id}" usa un dato desconocido: {${raw.trim()}}.`);
    }
  }
  return problems;
}

/** A field with its text already resolved, ready for the renderer. */
export interface ResolvedField {
  page: number;
  x: number;
  y: number;
  w: number;
  h: number;
  type: FieldType;
  text: string;
  /** Only for type "lines". */
  lines?: OrderLine[];
  fontSize?: number;
  lineHeight?: number;
  indent?: number;
  bold?: boolean;
  align?: "left" | "center" | "right";
  color?: string;
}

/** Pages of a PDF template that must not print for this order (their {onlyIf} data is empty). */
export function skippedPages(order: Order, rules: { page: number; onlyIf: string }[] | undefined): number[] {
  return (rules ?? []).filter((r) => !hasValue(variableByToken.get(r.onlyIf)?.resolve(order) ?? "")).map((r) => r.page);
}

export function resolveFields(order: Order, fields: TemplateField[]): ResolvedField[] {
  return fields.map((f) => {
    const value = f.text !== undefined && f.text !== "" ? fillText(order, f.text) : f.variable ? (byId.get(f.variable)?.resolve(order) ?? "") : "";
    const base = { page: f.page, x: f.x, y: f.y, w: f.w, h: f.h, type: f.type, fontSize: f.fontSize, lineHeight: f.lineHeight, indent: f.indent, bold: f.bold, align: f.align, color: f.color };
    if (f.type === "lines") return { ...base, text: "", lines: f.variable === "order.lines" ? order.lines : [] };
    if (f.type === "check") return { ...base, text: value ? "X" : "" };
    if (f.type === "sign") return { ...base, text: "" };
    return { ...base, text: value };
  });
}
