// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.
export interface FleetUnit {
  capacity: number;
  label: string;
}

/** Vehicle sizes MT Colectivo prices for. Later this can come from the fleet itself. */
export const DEFAULT_FLEET: FleetUnit[] = [
  { capacity: 6, label: "Van 6" },
  { capacity: 14, label: "Van 14" },
  { capacity: 20, label: "Van 20" },
  { capacity: 45, label: "Autobús 45" },
];

export const unitLabel = (capacity: number, fleet: FleetUnit[] = DEFAULT_FLEET) =>
  fleet.find((u) => u.capacity === capacity)?.label ?? `Unidad ${capacity}`;

/**
 * Smallest unit where everybody fits. Above the largest unit, fill it and
 * cover the remainder with the smallest unit that fits it.
 */
export function assignUnits(passengers: number, fleet: FleetUnit[] = DEFAULT_FLEET): number[] {
  if (!Number.isFinite(passengers) || passengers <= 0 || !fleet.length) return [];
  const caps = fleet.map((u) => u.capacity).sort((a, b) => a - b);
  const largest = caps[caps.length - 1];
  const units: number[] = [];
  let remaining = Math.ceil(passengers);
  while (remaining > largest) {
    units.push(largest);
    remaining -= largest;
  }
  units.push(caps.find((c) => c >= remaining) as number);
  return units;
}
