// Copies the pure order/pricing/document code from mtcolectivo-infra into src/shared,
// so the browser draws previews with exactly the code that draws the real PDF.
// Run after changing packages/core or packages/pdf there:  npm run sync:shared
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const infra = join(here, "..", "..", "mtcolectivo-infra", "packages");
const out = join(here, "..", "src", "shared");

const HEADER = "// GENERATED by scripts/sync-shared.mjs from mtcolectivo-infra. Do not edit here: change it there and run `npm run sync:shared`.\n";

const copies = [
  { from: join(infra, "core", "src"), to: join(out, "core"), files: ["folio", "format", "index", "orders", "pricing", "sample", "schemas", "templates", "units"] },
  { from: join(infra, "pdf", "src"), to: join(out, "pdf"), files: ["document", "render"] },
];

rmSync(out, { recursive: true, force: true });
for (const { from, to, files } of copies) {
  mkdirSync(to, { recursive: true });
  for (const name of files) {
    let code = readFileSync(join(from, `${name}.ts`), "utf8").replace(/\r\n/g, "\n");
    code = code.replace(/from "@mtcolectivo\/core"/g, 'from "../core"');
    // the seed prices only matter for loading the database
    code = code.replace(/^export \{ SEED_SERVICES_2025 \} from "\.\/seed\/services-2025";\n/m, "");
    writeFileSync(join(to, `${name}.ts`), HEADER + code);
  }
}
console.log("src/shared actualizado desde mtcolectivo-infra");
